### ISSUE TITLE
Empty file

### ISSUE THREAD

**Issue by snwefly** [zackmark29/iq.com-m3u8-parser#3]
Getting empty file when trying to download.

Thanks

Show is region locked to china and taiwan so please use vpn

https://www.iq.com/play/%E8%80%81%E5%B8%AB%E6%99%9A%E4%B8%8A%E5%A5%BD-episode-1-19rrljrmxs?lang=en_us#

**Comment by zackmark29** [comment]
Fixed  https://github.com/zackmark29/iq.com-m3u8-parser/commit/8462f463b23544fafd0c057e0903cdda448dd870
