### ISSUE TITLE
[Request] can you implement for grab all .m3u8 in playlist

### ISSUE THREAD

**Issue by cjrayance** [zackmark29/iq.com-m3u8-parser#4]
Your script works great. But I would like you to improve it for more comfortable use. because Some anime has a lot of episodes such as [Fullmetal Alchemist Brotherhood ](https://www.iq.com/album/fullmetal-alchemist-brotherhood-2009-2009-s8lu95if3p?lang=en_us ) has 64 episode or some TV show has more than 100++ episode, make me inconvenient to use your bookmarklet

 It might be a request that annoys you. Because you can say that Go and improve it by yourself or just clicks next episode.
  
 But I really want you to do it.

thank you !!

**Comment by zackmark29** [comment]
Ahm I don't think I have to add this feature. Because the purpose only of this bookmarklet is to grab and save m3u8 data of the current movie/episode being played.
Though I can do it and it's possible only in proper or automated script not like this :)

**Comment by cjrayance** [comment]
thank you, sir

and do you have plans to do that script?

**Comment by zackmark29** [comment]
> thank you, sir
> 
> and do you have plans to do that script?

Sorry, no plan to add it. I only made it for a friend, and that's all he wanted.
